apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reverdi-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/epqlffltm/reluxe-gitops.git
    targetRevision: HEAD
    path: charts/reverdi-app
    helm:
      valueFiles:
        - values-vagrant.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: reluxe
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true