apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reverdi.fullname" . }}-secret
  labels:
    {{- include "reverdi.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  SECRET_KEY: {{ .Values.env.SECRET_KEY | quote }}